services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: serendipitydb
      POSTGRES_USER: serenbhai
      POSTGRES_PASSWORD: serenbro
    ports:
      - "5432:5432"
    volumes:
      - serendipity_postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app_network

volumes:
  serendipity_postgres_data:

networks:
  app_network:
    external: true